### PR TITLE
account for empty strings in HTTPS_PROXY

### LINKED ISSUE #149: ValidationError: child "proxy" fails because ["proxy" is not allowed to be empty]?
When I try to use `nsp` I always have this error:
```
(+) ValidationError: child "proxy" fails because ["proxy" is not allowed to be empty]
```

I can reproduce it simply with:
```
$ npm init -f
$ npm i -S nsp
$ ./node_modules/.bin/nsp check
```

Nothing seems special about by npm config:
```
$ npm config list
; cli configs
user-agent = "npm/3.10.10 node/v6.9.4 darwin x64"

; userconfig /Users/noda/.npmrc
email = "<my_email>"
progress = false
registry = "https://registry.npmjs.org/"
strict-ssl = false

; globalconfig /usr/local/etc/npmrc
strict-ssl = false

; node bin location = /usr/local/bin/node
; cwd = /Users/noda/Desktop/nsp
; HOME = /Users/noda
; "npm config ls -l" to show all defaults.
```

I use OSX 10.12.1 (Sierra).

Any hints?

### PR DESCRIPTION
**Pull request by nlf**
closes #149

### CODE REVIEW

File: lib/check.js [hunk 1]
```diff
@@ -68,11 +68,12 @@ module.exports = function (options, callback) {
     options = {};
   }
 
-  options.proxy = options.proxy || Conf.proxy;
-  options.proxy = options.proxy || process.env.https_proxy || process.env.HTTPS_PROXY;
-  if (options.proxy) {
-    Conf.api.agent = new ProxyAgent(options.proxy);
-    delete options.proxy;
+  var proxy = options.proxy || Conf.proxy;
+  proxy = proxy || process.env.https_proxy || process.env.HTTPS_PROXY;
```
Comment (wraithgar) [inline lib/check.js:72]: Is there a reason this is two lines instead of one?

Comment (nlf) [reply lib/check.js:72]: it looks like it was this way to simplify coverage for tests. i left it so i didn't have to add even more tests to facilitate getting this change out quickly.

Comment (wraithgar) [reply lib/check.js:72]: good enough for me! :shipit:
